set_property SRC_FILE_INFO {cfile:{C:/Users/Philip Glynn/Desktop/POVDisplay/POVDisplay.srcs/constrs_1/imports/basys/Basys3_Master.xdc} rfile:../../../POVDisplay.srcs/constrs_1/imports/basys/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports led]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports hallSensor]
