# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Philip Glynn/POVDisplay/POVDisplay.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Philip Glynn/POVDisplay/POVDisplay.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Philip Glynn/POVDisplay/POVDisplay.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {{C:/Users/Philip Glynn/Desktop/Verilog/HDL files/povDisplay.sv}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Philip Glynn/POVDisplay/POVDisplay.srcs/constrs_1/imports/basys/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Philip Glynn/POVDisplay/POVDisplay.srcs/constrs_1/imports/basys/Basys3_Master.xdc}}]


synth_design -top arrays_data -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef arrays_data.dcp

catch { report_utilization -file arrays_data_utilization_synth.rpt -pb arrays_data_utilization_synth.pb }
